In [18]:
# Minimal repro: index says CHLA should be "A", but argopy (expert mode) shows "" for CHLA_DATA_MODE

import numpy as np
from argopy import DataFetcher as ArgoDataFetcher

wmo = 4902627
cyc = 18
region = [-70, -40, 20, 60, 0, 1000, "2024-03-01", "2024-04-01"]
target_file = "meds/4902627/profiles/SR4902627_018.nc"

# 1) Fetch in expert mode (so nothing gets dropped by standard-mode filtering)
fetcher = ArgoDataFetcher(
    mode="expert",
    ds="bgc",
    src="erddap",
    params=["CHLA", "PRES"],
).region(region)

# 3) Show what the Argo synthetic-profile index says for the same float/cycle
idx = fetcher.fetcher.indexfs
idx.query.wmo([wmo])
idf = idx.to_dataframe(completed=False)
idf[((idf["wmo"] == wmo) & (idf["cyc"] == cyc))]

/tmp/ipykernel_21882/1306906081.py:22: FutureWarning: Note that the long name for institution is now in 'institution_name' while the 'institution' column will hold the institution code -- Deprecated since version 1.4
  idf = idx.to_dataframe(completed=False)

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update,wmo,cyc
30,meds/4902627/profiles/SR4902627_018.nc,2024-03-04 17:25:00,42.484,-60.269,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:56:11,4902627,18
31,meds/4902627/profiles/SR4902627_018D.nc,2024-02-23 23:52:00,NaN,NaN,NaN,836,ME,PRES PSAL TEMP DOXY PH_IN_SITU_TOTAL,RRRRR,2025-08-27 21:56:00,4902627,18

In [19]:
print(idf[((idf["wmo"] == wmo) & (idf["cyc"] == cyc))])

                                       file                date  latitude  \
30   meds/4902627/profiles/SR4902627_018.nc 2024-03-04 17:25:00    42.484
31  meds/4902627/profiles/SR4902627_018D.nc 2024-02-23 23:52:00       NaN

    longitude ocean  profiler_type institution  \
30    -60.269     A            836          ME
31        NaN   NaN            836          ME

                                          parameters parameter_data_mode  \
30  PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL             RRRRARR
31              PRES PSAL TEMP DOXY PH_IN_SITU_TOTAL               RRRRR

           date_update      wmo  cyc
30 2025-08-27 21:56:11  4902627   18
31 2025-08-27 21:56:00  4902627   18

In [21]:
import argopy
argopy.show_versions()

SYSTEM
------
commit: None
python: 3.12.12 | packaged by conda-forge | (main, Oct 22 2025, 23:25:55) [GCC 14.3.0]
python-bits: 64
OS: Linux
OS-release: 6.12.64-87.122.amzn2023.x86_64
machine: x86_64
processor: x86_64
byteorder: little
LC_ALL: en_US.UTF-8
LANG: en_US.UTF-8
LOCALE: en_US.UTF-8
libhdf5: 1.14.3
libnetcdf: 4.9.2

INSTALLED VERSIONS: CORE
------------------------
aiohttp     : 3.12.15
argopy      : 1.4.0
decorator   : 5.2.1
erddapy     : 2.3.0
fsspec      : 2025.12.0
h5netcdf    : 1.7.3
netCDF4     : 1.7.2
packaging   : 25.0
requests    : 2.32.5
scipy       : 1.16.3
toolz       : 1.1.0
xarray      : 2025.9.0

INSTALLED VERSIONS: EXT.UTIL
----------------------------
gsw         : -
pyco2sys    : -
tqdm        : 4.67.1

INSTALLED VERSIONS: EXT.FILES
-----------------------------
boto3       : 1.40.70
kerchunk    : 0.2.9
numcodecs   : 0.16.5
s3fs        : 2025.12.0
zarr        : 3.1.5

INSTALLED VERSIONS: EXT.PERF
----------------------------
dask        : 2025.11.0
distributed : 2025.11.0
joblib      : 1.5.3
numba       : 0.63.1
pyarrow     : 18.1.0

INSTALLED VERSIONS: EXT.PLOT
----------------------------
IPython     : 9.8.0
cartopy     : 0.25.0
ipykernel   : 7.1.0
ipywidgets  : 8.1.8
matplotlib  : 3.10.8
pyproj      : 3.7.1
seaborn     : 0.13.2

INSTALLED VERSIONS: DEV
-----------------------
aiofiles    : -
black       : -
bottleneck  : -
cfgrib      : -
cftime      : 1.6.5
codespell   : -
flake8      : -
numpy       : 2.3.5
pandas      : 2.3.3
pip         : 25.3
pytest      : 9.0.2
pytest_cov  : 7.0.0
pytest_env  : -
pytest_localftpserver: -
setuptools  : 80.9.0
sphinx      : 9.0.4

INSTALLED VERSIONS: PIP
-----------------------
pytest-reportlog: -

In [10]:
# 1) Fetch in expert mode (so nothing gets dropped by standard-mode filtering)
fetcher = ArgoDataFetcher(
    mode="expert",
    ds="bgc",
    src="erddap",
    params=["CHLA", "PRES"],
).region(region)
idx = fetcher.fetcher.indexfs
idf = idx.to_dataframe(completed=False)

/tmp/ipykernel_21882/2603856950.py:9: FutureWarning: Note that the long name for institution is now in 'institution_name' while the 'institution' column will hold the institution code -- Deprecated since version 1.4
  idf = idx.to_dataframe(completed=False)

Empty DataFrame
Columns: [wmo, cyc, n]
Index: []

In [13]:
idf[(idf["file"] == target_file) | ((idf["wmo"] == wmo) & (idf["cyc"] == cyc))]

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update,wmo,cyc
89,meds/4902627/profiles/SR4902627_018.nc,2024-03-04 17:25:00,42.484,-60.269,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:56:11,4902627,18

In [12]:
dups = (
    idf.groupby(["wmo", "cyc"])
       .size()
       .reset_index(name="n")
       .query("n > 1")
)

dups

Empty DataFrame
Columns: [wmo, cyc, n]
Index: []

In [11]:
idf

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update,wmo,cyc
0,aoml/1902383/profiles/SD1902383_078.nc,2024-03-02 16:13:24,23.021,-53.222,A,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP...,AAAAAAARAD,2026-01-06 13:25:02,1902383,78
1,aoml/1902383/profiles/SD1902383_079.nc,2024-03-12 15:19:00,22.728,-52.393,A,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP...,AAAAAAARAD,2026-01-06 13:25:12,1902383,79
2,aoml/1902383/profiles/SD1902383_080.nc,2024-03-22 15:28:33,23.265,-52.001,A,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP...,AAAAAAARAD,2026-01-06 13:25:22,1902383,80
3,aoml/1902384/profiles/SD1902384_079.nc,2024-03-08 20:58:18,20.015,-42.710,A,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP...,AAAAAAARDD,2026-01-03 10:24:40,1902384,79
4,aoml/1902384/profiles/SD1902384_080.nc,2024-03-18 20:31:41,20.302,-42.553,A,869,AO,PRES TEMP PSAL DOXY CHLA CHLA_FLUORESCENCE BBP...,AAAAAAARDD,2026-01-03 10:24:50,1902384,80
...,...,...,...,...,...,...,...,...,...,...,...,...
99,meds/4902685/profiles/SR4902685_025.nc,2024-03-09 21:10:00,58.249,-49.247,A,834,ME,PRES TEMP PSAL DOXY DOWN_IRRADIANCE380 DOWN_IR...,RRRRRRRRAR,2025-12-22 22:50:55,4902685,25
100,meds/4902685/profiles/SR4902685_026.nc,2024-03-15 02:24:00,58.427,-49.221,A,834,ME,PRES TEMP PSAL DOXY DOWN_IRRADIANCE380 DOWN_IR...,RRRRRRRRAR,2025-09-16 23:15:39,4902685,26
101,meds/4902685/profiles/SR4902685_027.nc,2024-03-20 07:26:00,58.441,-49.667,A,834,ME,PRES TEMP PSAL DOXY DOWN_IRRADIANCE380 DOWN_IR...,RRRRRRRRAR,2025-09-16 23:15:49,4902685,27
102,meds/4902685/profiles/SR4902685_028.nc,2024-03-25 12:26:00,58.411,-49.609,A,834,ME,PRES TEMP PSAL DOXY DOWN_IRRADIANCE380 DOWN_IR...,RRRRRRRRAR,2025-12-22 22:51:05,4902685,28
103,meds/4902685/profiles/SR4902685_029.nc,2024-03-30 17:43:00,58.382,-49.552,A,834,ME,PRES TEMP PSAL DOXY DOWN_IRRADIANCE380 DOWN_IR...,RRRRRRRRAR,2025-12-22 22:51:16,4902685,29

In [8]:
idf.head()

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update,wmo,cyc
0,meds/4902627/profiles/SR4902627_001.nc,2023-09-16 11:28:00,43.498,-57.755,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:50:16,4902627,1
1,meds/4902627/profiles/SR4902627_001D.nc,2023-09-15 04:28:00,43.498,-57.755,A,836,ME,PRES PSAL TEMP DOXY PH_IN_SITU_TOTAL,RRRRR,2025-08-27 21:50:05,4902627,1
2,meds/4902627/profiles/SR4902627_002.nc,2023-09-26 20:24:00,43.084,-58.321,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:50:41,4902627,2
3,meds/4902627/profiles/SR4902627_002D.nc,2023-09-16 12:59:00,43.084,-58.321,A,836,ME,PRES PSAL TEMP DOXY PH_IN_SITU_TOTAL,RRRRR,2025-08-27 21:50:30,4902627,2
4,meds/4902627/profiles/SR4902627_003.nc,2023-10-06 15:29:00,42.705,-57.995,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:51:03,4902627,3

In [5]:
idf = idx.to_dataframe(completed=False)
idf[(idf["file"] == target_file) | ((idf["wmo"] == wmo) & (idf["cyc"] == cyc))]

/tmp/ipykernel_21882/2161587937.py:1: FutureWarning: Note that the long name for institution is now in 'institution_name' while the 'institution' column will hold the institution code -- Deprecated since version 1.4
  idf = idx.to_dataframe(completed=False)

,file,date,latitude,longitude,ocean,profiler_type,institution,parameters,parameter_data_mode,date_update,wmo,cyc
30,meds/4902627/profiles/SR4902627_018.nc,2024-03-04 17:25:00,42.484,-60.269,A,836,ME,PRES PSAL TEMP DOXY CHLA BBP700 PH_IN_SITU_TOTAL,RRRRARR,2025-08-27 21:56:11,4902627,18
31,meds/4902627/profiles/SR4902627_018D.nc,2024-02-23 23:52:00,NaN,NaN,NaN,836,ME,PRES PSAL TEMP DOXY PH_IN_SITU_TOTAL,RRRRR,2025-08-27 21:56:00,4902627,18

In [3]:
from argopy import DataFetcher as ArgoDataFetcher

wmo = 4902627

# Create a selection so the underlying fetcher gets instantiated:
fetcher = ArgoDataFetcher(
    mode="expert",
    ds="bgc",
    src="erddap",
    params=["CHLA", "PRES"],
).wmo([wmo])

# Now the internal fetcher exists and has the index store:
idx = fetcher.fetcher.indexfs

idx.query.wmo([wmo])
idf = idx.to_dataframe(completed=False)

matches = idf[
    idf["file"].isin([
        "meds/4902627/profiles/SR4902627_018.nc",
        "meds/4902627/profiles/SR4902627_018D.nc",
    ])
][["file", "parameters", "parameter_data_mode", "date_update"]]

print(matches.to_string(index=False))

InvalidFetcherAccessPoint: 'wmo' is not a valid access point

In [ ]:
from argopy import DataFetcher as ArgoDataFetcher
# specify the data set and what source
fetcher = ArgoDataFetcher(
    ds="bgc",
    src="erddap",
    params=["CHLA", "PRES"] # both these need to be present
)
# specify that we want to access data in a region; a NW Atlantic box
# lon_min, lon_max, lat_min, lat_max, depth_min, depth_max, time_min, time_max
region = [-70, -40, 20, 60, 0, 1000, "2024-03-01", "2024-04-01"]
fetcher = fetcher.region(region)
ds_na = fetcher.to_xarray()
df = ds_na.to_dataframe().reset_index()

In [ ]:
out = (
    df[
        [
            "PLATFORM_NUMBER",
            "CYCLE_NUMBER",
            "DIRECTION",
            "TIME",
            "LATITUDE",
            "LONGITUDE",
            "PRES",
            "TEMP",
            "PSAL",
            "CHLA",
            "PRES_QC",
            "TEMP_QC",
            "PSAL_QC",
            "CHLA_QC",
        ]
    ]
    .rename(
        columns={
            "PLATFORM_NUMBER": "platform_number",
            "CYCLE_NUMBER": "cycle_number",
            "DIRECTION": "direction",
            "TIME": "time",
            "LATITUDE": "latitude",
            "LONGITUDE": "longitude",
        }
    )
)
out.to_csv("argo_profiles.csv", index=False)